"""create ShippingRate Table and adding shipping_price to order table

Revision ID: 019dad5a6bb2
Revises: f02057564216
Create Date: 2025-04-25 04:42:21.475389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019dad5a6bb2'
down_revision: Union[str, None] = 'f02057564216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rates',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('orders', sa.Column('shipping_rate_uid', sa.Uuid(), nullable=False))
    op.add_column('orders', sa.Column('shipping_price', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'orders', 'shipping_rates', ['shipping_rate_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_price')
    op.drop_column('orders', 'shipping_rate_uid')
    op.drop_table('shipping_rates')
    # ### end Alembic commands ###
