"""edit product_uid in variant_group table from product_id to product_uid

Revision ID: 0ccb108b3057
Revises: 76142428d042
Create Date: 2025-04-27 17:41:03.328905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ccb108b3057'
down_revision: Union[str, None] = '76142428d042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_groups', sa.Column('product_uid', sa.Uuid(), nullable=False))
    op.drop_constraint('variant_groups_product_id_fkey', 'variant_groups', type_='foreignkey')
    op.create_foreign_key(None, 'variant_groups', 'products', ['product_uid'], ['uid'])
    op.drop_column('variant_groups', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_groups', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'variant_groups', type_='foreignkey')
    op.create_foreign_key('variant_groups_product_id_fkey', 'variant_groups', 'products', ['product_id'], ['uid'])
    op.drop_column('variant_groups', 'product_uid')
    # ### end Alembic commands ###
