"""adding quantity and stock_availability to the product

Revision ID: 1cd9e3918843
Revises: 4dab3413ce9a
Create Date: 2025-04-20 10:42:25.090523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd9e3918843'
down_revision: Union[str, None] = '4dab3413ce9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('stock_availability', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_availability')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
