"""add cost_price to the product

Revision ID: 2a50e5fad726
Revises: 0d450712891d
Create Date: 2025-05-28 10:24:43.025838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a50e5fad726'
down_revision: Union[str, None] = '0d450712891d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
