"""update carts table to accept variant_choice_id

Revision ID: 31790ed1fc51
Revises: dc4f217fbfd7
Create Date: 2025-04-26 19:00:06.880580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31790ed1fc51'
down_revision: Union[str, None] = 'dc4f217fbfd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('variant_choice_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'carts', 'variant_choices', ['variant_choice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'variant_choice_id')
    # ### end Alembic commands ###
