"""change the name is_visible in products table to is_active

Revision ID: 41e3145a7db7
Revises: 9be58b63bbb4
Create Date: 2025-05-04 00:37:26.310169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e3145a7db7'
down_revision: Union[str, None] = '9be58b63bbb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.drop_column('products', 'is_visible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_visible', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
