"""Update an Order Table and Shipping_Address Table

Revision ID: 463621f58917
Revises: 05ea0324e082
Create Date: 2025-04-25 03:41:15.378722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463621f58917'
down_revision: Union[str, None] = '05ea0324e082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'orders', 'shipping_address', ['shipping_address'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###
