"""adding new and old price to the product

Revision ID: 4dab3413ce9a
Revises: cdd5920ce0cf
Create Date: 2025-04-20 09:48:49.596380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dab3413ce9a'
down_revision: Union[str, None] = 'cdd5920ce0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('old_price', sa.Float(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('new_price', sa.Float(), nullable=False, server_default='0'))
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('products', 'new_price')
    op.drop_column('products', 'old_price')
    # ### end Alembic commands ###
