"""add image to category

Revision ID: 5d58cefae200
Revises: be033e907c2e
Create Date: 2025-05-06 10:58:44.932581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d58cefae200'
down_revision: Union[str, None] = 'be033e907c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First add the column as nullable
    op.add_column('categories', sa.Column('image', sa.String(), nullable=True))
    
    # Update existing rows with a default image path
    op.execute("UPDATE categories SET image = 'default_category_image.jpg'")
    
    # Make the column non-nullable
    op.alter_column('categories', 'image', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
