"""make stock in products required

Revision ID: 607875e7b6dd
Revises: 58f71c1d17f8
Create Date: 2025-05-06 09:58:06.665792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607875e7b6dd'
down_revision: Union[str, None] = '58f71c1d17f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
