"""Add VariantGroup and VariantChoice Tables

Revision ID: 7d0fbede5252
Revises: 019dad5a6bb2
Create Date: 2025-04-26 18:11:55.830014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0fbede5252'
down_revision: Union[str, None] = '019dad5a6bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant_choices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['variant_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('orders', 'shipping_rate_uid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_rate_uid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('variant_choices')
    op.drop_table('variant_groups')
    # ### end Alembic commands ###
