"""Add category_uid foreign key to products table

Revision ID: 878e9d0c2e7d
Revises: ea5105bd2a5d
Create Date: 2025-04-20 11:55:54.827678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878e9d0c2e7d'
down_revision: Union[str, None] = 'ea5105bd2a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['category_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_uid')
    # ### end Alembic commands ###
