"""add extra_price to variant choice

Revision ID: b181902c6d76
Revises: 5d58cefae200
Create Date: 2025-05-10 00:56:48.466225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b181902c6d76'
down_revision: Union[str, None] = '5d58cefae200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_choices', sa.Column('extra_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_choices', 'extra_price')
    # ### end Alembic commands ###
