"""Edit VariantChoice stock to be optional Tables

Revision ID: dc4f217fbfd7
Revises: 7d0fbede5252
Create Date: 2025-04-26 18:43:35.883529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4f217fbfd7'
down_revision: Union[str, None] = '7d0fbede5252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variant_choices', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variant_choices', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
