"""update products table to accept stock and remove in_stock and quantity

Revision ID: e24fa35e3cba
Revises: 0ccb108b3057
Create Date: 2025-04-27 18:16:46.743241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24fa35e3cba'
down_revision: Union[str, None] = '0ccb108b3057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'in_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('in_stock', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
