"""change the name of the stock availability to in_stock

Revision ID: ef70fa773a7c
Revises: 04f434148d8f
Create Date: 2025-04-23 09:25:55.170473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef70fa773a7c'
down_revision: Union[str, None] = '04f434148d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('in_stock', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.drop_column('products', 'stock_availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_availability', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('products', 'in_stock')
    # ### end Alembic commands ###
